import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BMCC Summer 20202 Starter App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          BMCC Summer 20202 - <a href="https://nextjs.org">Next.js</a> Starter App
        </h1>

        <p className={styles.description}>
          Quick start: change this page by editing:{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>


        <h2>What's in this starer</h2>
        <ul>
          <li>This page, editable at: {' '} <code>pages/index.js</code></li>
          <li><a href="/about">/about</a>, editable at: {' '} <code>pages/about/index.js</code>, which contains some component examples</li>
          <li><a href="/contact">/contact</a>, editable at: {' '} <code>pages/contact/index.js</code> which contains a database example</li>
        </ul>
        
        <h2>External resources</h2>
        <div className={styles.grid}>
          <a href="https://eloquentjavascript.net/" className={styles.card}>
            <h2>Eloquent JS &rarr;</h2>
            <p>Learn about JavaScript, functional programming, the DOM, and Node - from the free, online Eloquent JavaScript book</p>
          </a>

          
          <a href="https://nextjs.org/learn/foundations/about-nextjs" className={styles.card}>
            <h2>Next.JS &rarr;</h2>
            <p>Tutorial(s) about React and Next.JS</p>
          </a>

          <a href="https://docs.google.com/document/d/1l-hxTTd23rcIlmX58V-yHFPNJKMs-4E3ZsoFuh_Sye0/edit#" className={styles.card}>
            <h2>More &rarr;</h2>
            <p>Check out Dan's Google Doc with more resources and links</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Vercel
            and Replit
        </a>
      </footer>
    </div>
  )
}
