import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BMCC Summer 20202 Starter App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          BMCC Summer 20202 - NextJS Starter App
        </h1>

        <p className={styles.description}>
          Fork this repl, then choose a database per <a href="https://docs.google.com/document/d/1l-hxTTd23rcIlmX58V-yHFPNJKMs-4E3ZsoFuh_Sye0/edit#">Dan's google doc</a>
        </p>


        <h2>Mapping URLs to files</h2>
        <ul>
          <li>Paths in the <code>/pages</code> directory create pages in the app. </li>
          <li>This page (the home page) is editable at: {' '} <code>pages/index.js</code></li>
          <li><a href="/examples/react-components/bootstrap">/examples/react-components/bootstrap</a> is editable at <code>pages/examples/react-components/bootstap/index.jsx</code></li>
        </ul>

        <h2>UI Examples</h2>
        <ul>
          <li><a href="/examples/react-components/custom">/examples/react-components/custom</a></li>
          <li><a href="/examples/react-components/mui">/examples/react-components/mui</a></li>
          <li><a href="/examples/react-components/nextjs">/examples/react-components/nextjs</a></li>
        </ul>

        <h2>Database Examples</h2>
        <ul>
          <li><a href="/examples/databases/replit-db">/examples/databases/replit-db</a></li>
          <li><a href="/examples/databases/postgresql">/examples/databases/postgresql</a></li>
          <li><a href="/examples/databases/mongodb">/examples/databases/mongodb</a></li>
        </ul>
        
        <h2>External resources</h2>
        <div className={styles.grid}>
          <a href="https://eloquentjavascript.net/" className={styles.card}>
            <h2>Eloquent JS &rarr;</h2>
            <p>Learn about JavaScript, functional programming, the DOM, and Node - from the free, online Eloquent JavaScript book</p>
          </a>

          
          <a href="https://nextjs.org/learn/foundations/about-nextjs" className={styles.card}>
            <h2>Next.JS &rarr;</h2>
            <p>Tutorial(s) about React and Next.JS</p>
          </a>

          <a href="https://docs.google.com/document/d/1l-hxTTd23rcIlmX58V-yHFPNJKMs-4E3ZsoFuh_Sye0/edit#" className={styles.card}>
            <h2>More &rarr;</h2>
            <p>Check out Dan's Google Doc with more resources and links</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Vercel
            and Replit
        </a>
      </footer>
    </div>
  )
}
